"""Concept-bundle prompt-cue study on language-model reasoning.

This pilot tested whether flooding a language model with several rephrasings of
the same underlying meaning (a "concept bundle") steers reasoning more reliably
than control conditions like exact repetition or surface lexical overlap.

Two artifacts survived the closure:

- A controlled, synthetic four-family benchmark (Boolean logic, ordering,
  state tracking, temporal reasoning) generated by `src.build_benchmark`.
- A decoupled evaluation that scores the "solve" step and the "bind to an
  answer choice" step separately, run by `src.run_decoupled_eval`.

See `reports/project_closure_report_20260327.md` for the closure findings and
`GLOSSARY.md` for the internal vocabulary used across these files.
"""

